# buildifier: disable=no-effect
cxx_binary(
    name = "app",
    srcs = ["main.cpp"],
    link_style = "static",
    deps = ["//lib:library",
            "//third-party:argparse",
            "//third-party:gmp",
            "//third-party:gmpxx"],
    visibility = ["PUBLIC"],
)
