# buildifier: disable=no-effect
cxx_library(
    name = "library",
    srcs = glob(["*.cpp"]),
    exported_headers = ["./lib.hpp"],
    link_style = "static",
    deps = ["//third-party:gmp",
            "//third-party:gmpxx"],
    visibility = ["PUBLIC"],
)
